# Importing Numpy Libraries

In [1]:
import numpy as np

In [2]:
lst = [1,2,3]

In [3]:
arr = np.array(lst)

In [4]:
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

In [8]:
arr_a = np.array([[1,2,3],[4,5,6]])
arr_a

array([[1, 2, 3],
       [4, 5, 6]])

# Indexing

In [9]:
arr_a[1]

array([4, 5, 6])

In [10]:
arr_a[1][2]

6

In [11]:
arr_a[1,2]

6

In [14]:
arr_a[:,1]

array([2, 5])

In [15]:
arr_a[-1]

array([4, 5, 6])

# Assigning Values

In [16]:
arr_a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr_a[0,2] = 18

In [19]:
arr_a

array([[ 1,  2, 18],
       [ 4,  5,  6]])

In [20]:
arr_a[0] = 9
arr_a

array([[9, 9, 9],
       [4, 5, 6]])

In [21]:
arr_a[:,1] = 5

In [22]:
arr_a

array([[9, 5, 9],
       [4, 5, 6]])

In [25]:
lst_a = [1,9,7]
arr_a[0] = lst_a
arr_a

array([[1, 9, 7],
       [4, 5, 6]])

In [26]:
lst_b = [2,3]
arr_a[:,2] = lst_b
arr_a

array([[1, 9, 2],
       [4, 5, 3]])

In [27]:
arr_a[:] = 8
arr_a

array([[8, 8, 8],
       [8, 8, 8]])

# Elementwise Properties

In [28]:
arr_a = np.array([7,8,9])
arr_b = np.array([[1,2,3],[4,5,6]])

In [29]:
arr_a

array([7, 8, 9])

In [30]:
arr_b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr_b*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
lst_a = [1,2,3]
lst_a+[2]

[1, 2, 3, 2]

In [35]:
arr_a + 2

array([ 9, 10, 11])

In [37]:
arr_b[1]*arr_a

array([28, 40, 54])

In [42]:
arr_x = np.array([[1],[2]])
mat_C = np.array([[1,2,3],[4,5,6]])

In [44]:
arr_x

array([[1],
       [2]])

In [45]:
mat_C

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.add(arr_x,mat_C)

array([[2, 3, 4],
       [6, 7, 8]])

# Data Types

In [38]:
np.array([[1,2,3],[4,5,6]],dtype = np.float16)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [39]:
np.array([[1,2,3],[4,5,6]],dtype = np.complex64)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [40]:
np.array([[1,2,3],[4,5,6]],dtype = str)

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')