In [1]:
import numpy as np

# Slicing


#### Basic Slicing

In [2]:
mat_A = np.array([[1,2,3],[4,5,6]])
mat_A

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
mat_A[:,:2]

array([[1, 2],
       [4, 5]])

In [6]:
mat_A[:,1:]

array([[2, 3],
       [5, 6]])

In [7]:
mat_A[1:,1:]

array([[5, 6]])

#### Stepwise Slicing

In [8]:
mat_B = np.array([[1,2,1,4,9],[3,2,7,5,9],[1,4,2,6,8]])
mat_B

array([[1, 2, 1, 4, 9],
       [3, 2, 7, 5, 9],
       [1, 4, 2, 6, 8]])

#sytax [start:stop:step]

[1,2,8]
[3,7,9]
[1,1,9]

In [19]:
mat_B[::-1,::2]

array([[1, 2, 8],
       [3, 7, 9],
       [1, 1, 9]])

# Conditional Slicing

In [22]:
mat_C = np.array([[3,1,5,6,2],[8,4,4,1,0],[3,8,5,9,2]])
mat_C

array([[3, 1, 5, 6, 2],
       [8, 4, 4, 1, 0],
       [3, 8, 5, 9, 2]])

In [23]:
mat_C[:,1]

array([1, 4, 8])

In [24]:
mat_C[:,1] > 3

array([False,  True,  True])

In [25]:
mat_C[:,:] > 3

array([[False, False,  True,  True, False],
       [ True,  True,  True, False, False],
       [False,  True,  True,  True, False]])

In [26]:
mat_C[mat_C[:,:]%2 == 0 ]

array([6, 2, 8, 4, 4, 0, 8, 2])

In [27]:
mat_C[(mat_C[:,:]%2 == 0) & (mat_C[:,:] < 5) ]

array([2, 4, 4, 0, 2])

In [28]:
mat_C[(mat_C[:,:]%2 == 0) | (mat_C[:,:] < 5) ]

array([3, 1, 6, 2, 8, 4, 4, 1, 0, 3, 8, 2])

# Shape

In [44]:
mat_C.shape

(3, 5)

# Exercise

In [30]:
array_1 = np.array([10,11,12,13,14])
array_2 = np.array([[20,30,40,50,60],[43,21,34,78,42],[12,32,65,45,34]])
array_3 = np.array([[[1,2,3,4,5],[11,12,13,14,15]],[[21,22,23,24,25],[31,32,33,34,35]]])

In [35]:
#slice last two column of 2nd row of array_2
array_2[1,-2:]

array([78, 42])

In [37]:
#slice 2nd row of array_2 excluding the last two columns
array_2[1,:-2]

array([43, 21, 34])

In [38]:
#slice 1st, 3rd, 5th columns of array_2
array_2[:,::2]

array([[20, 40, 60],
       [43, 34, 42],
       [12, 65, 34]])

In [ ]:
#use conditional slicing to check individual elements of  array satisfy this conditon :greater than 20
#display resultant arrays
#use conditional slicing to check individual elements of  array satisfy either of these conditons :1. greater than 20, 2. odd 
#use conditional slicing to check individual elements of  array satisfy both of these conditons :1. greater than 20, 2. odd 

In [39]:
array_2 > 20

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [40]:
array_2[array_2>20]

array([30, 40, 50, 60, 43, 21, 34, 78, 42, 32, 65, 45, 34])

In [41]:
array_2[(array_2>20) | (array_2%2 ==1)]

array([30, 40, 50, 60, 43, 21, 34, 78, 42, 32, 65, 45, 34])

In [46]:
array_2[(array_2>20) & (array_2%2 ==1)]

array([43, 21, 65, 45])

In [50]:
array_1.shape

(5,)