In [1]:
import numpy as np

## empty, zeros, ones, full

In [6]:
arr_empty = np.empty(shape=(3,3))
arr_empty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr_zeros = np.zeros(shape=(2,3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr_ones = np.ones(shape=(2,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr_full_2 = np.full(shape=(2,3), fill_value=2)
arr_full_2

array([[2, 2, 2],
       [2, 2, 2]])

In [10]:
arr_full_str = np.full(shape=(2,3), fill_value='Machine Learning')
arr_full_str

array([['Machine Learning', 'Machine Learning', 'Machine Learning'],
       ['Machine Learning', 'Machine Learning', 'Machine Learning']],
      dtype='<U16')

## np.arange

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange( start = 5,step = 10, stop= 26)

array([ 5, 15, 25])

In [19]:
np.arange(5,10,26)

array([5])

In [20]:
np.arange(5,26,10)

array([ 5, 15, 25])

In [21]:
np.arange( start = 5,step = 2.5, stop= 26)

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ])

In [22]:
np.arange( start = 5,step = 10, stop= 26, dtype= float)

array([ 5., 15., 25.])

## linspace

In [23]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

## Generating Random Numbers

In [24]:
np.random.rand(3)   #random samples from uniform distribution over [0,1)

array([0.84514936, 0.4496943 , 0.44555321])

In [25]:
np.random.rand(5,5)

array([[0.36285571, 0.93605998, 0.02232472, 0.26122195, 0.46335088],
       [0.15818445, 0.20921662, 0.23222965, 0.85224371, 0.30123692],
       [0.66637943, 0.62010136, 0.89879641, 0.75375452, 0.7299438 ],
       [0.75930195, 0.83671739, 0.49905138, 0.30614898, 0.12630643],
       [0.5616584 , 0.14742833, 0.03802335, 0.13320247, 0.35709558]])

In [28]:
np.random.randn(10,10)  #standard normal distribution

array([[ 0.50721957,  1.4470234 ,  0.3060729 , -0.29085326,  1.65209848,
        -0.57741469, -1.70721693, -1.63911249,  0.17141302, -0.58363441],
       [-0.74830384,  1.06368181,  1.20047139,  1.62810914, -0.94824847,
        -1.26977568,  0.89012296, -0.46888612,  0.45604366, -0.28102013],
       [-1.86115096,  0.0871151 , -1.08144246,  0.57528372, -1.70754072,
         0.88316137, -0.28654061,  2.31536551,  0.89791284,  0.70554306],
       [ 1.10627428,  0.25916683, -0.20697041, -0.10289898,  1.35607582,
        -2.18256522,  0.96015091,  2.13882893,  0.27628163, -0.39088034],
       [ 0.15801379,  0.92763473, -0.63051836, -0.35287626,  0.86765115,
         0.62394184, -1.00711952, -1.02384802,  0.9711302 , -0.06505313],
       [ 0.32682646, -0.77876738,  0.14295083, -0.36432957, -2.17658132,
         0.47248597,  1.32478053, -0.02900339, -0.0396277 ,  1.06237244],
       [-0.01739658, -0.74645351, -1.05499536, -0.94698864,  0.51148913,
         1.87144147, -0.27860017,  0.40967775

In [36]:
np.random.randint(1,10) 

8

In [38]:
np.random.randint(1,10,5)

array([5, 3, 9, 2, 8])

## seed

In [69]:
np.random.seed(50)  #random_state
np.random.randint(50,100,4)

array([98, 82, 61, 95])

# Reshape

In [75]:
arr = np.arange(40)

In [79]:
arr.reshape(8,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [80]:
lin1 = np.linspace(0,10,15)
lin1.reshape(3,5)

array([[ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286],
       [ 3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143],
       [ 7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ]])

In [83]:
np.arange(start=25,step = 2.5, stop=46, dtype=float).reshape(3,3)

array([[25. , 27.5, 30. ],
       [32.5, 35. , 37.5],
       [40. , 42.5, 45. ]])