In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr/arr

C:\Users\shrey\AppData\Local\Temp\ipykernel_14704\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
1/arr

C:\Users\shrey\AppData\Local\Temp\ipykernel_14704\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Universal Array Functions


In [9]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
np.log(arr)

C:\Users\shrey\AppData\Local\Temp\ipykernel_14704\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [12]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## Summary Statistics

In [25]:

arr = np.random.randint(0,50,20)

In [26]:
arr

array([49, 24, 34, 20, 38, 11,  2, 38, 36,  7, 33, 29, 21, 17, 19, 47, 41,
        8, 19, 14])

In [27]:
arr.sum()

507

In [28]:
arr.mean()

25.35

In [29]:
arr.max()

49

In [30]:
arr.min()

2

In [31]:
arr.var()

178.52750000000003

In [32]:
arr.std()

13.36141833788614

In [33]:
arr.argmin()

6

In [34]:
arr.argmax()

0

## Axis Logic

In [20]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr_2d.sum()

78

In [22]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [23]:
arr_2d.sum(axis=1)

array([10, 26, 42])

## Broadcasting

In [35]:
arr

array([49, 24, 34, 20, 38, 11,  2, 38, 36,  7, 33, 29, 21, 17, 19, 47, 41,
        8, 19, 14])

In [36]:
arr[0:5] = 10
arr

array([10, 10, 10, 10, 10, 11,  2, 38, 36,  7, 33, 29, 21, 17, 19, 47, 41,
        8, 19, 14])

In [37]:
slice_of_arr = arr[0:9]

In [38]:
slice_of_arr

array([10, 10, 10, 10, 10, 11,  2, 38, 36])

In [39]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99])

In [40]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99,  7, 33, 29, 21, 17, 19, 47, 41,
        8, 19, 14])

##### Reason: Data is not copied, it's just a view of original array. This is done to avoid memory problems

In [46]:
arr_copy = arr.copy()

In [47]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99,  7, 33, 29, 21, 17, 19, 47, 41,
        8, 19, 14])

In [48]:
slice_of_arr1 = arr_copy[0:9]

In [49]:
slice_of_arr1[:] = 59
slice_of_arr1

array([59, 59, 59, 59, 59, 59, 59, 59, 59])

In [51]:
arr_copy

array([59, 59, 59, 59, 59, 59, 59, 59, 59,  7, 33, 29, 21, 17, 19, 47, 41,
        8, 19, 14])

In [52]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99,  7, 33, 29, 21, 17, 19, 47, 41,
        8, 19, 14])